version: '3'
services:

  petclinic-db.default.svc.cluster.local:
    image: sdaaslan/purple-project-db:1.0.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=demo
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  petclinic:
    depends_on:
    - petclinic-db.default.svc.cluster.local
    image: sdaaslan/purple-project:1.0.0
    ports:
      - "80:8080"
#      - "8000:8000"
